production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    memory: 1G
    path: <%= ENV['SOLR_PATH'] || '/solr/seek' %>
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: <%= ENV['SOLR_PATH'] || '/solr/seek' %>

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    